
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 668)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lbBot = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.lbBot.setFont(font)
        self.lbBot.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lbBot.setAlignment(QtCore.Qt.AlignCenter)
        self.lbBot.setObjectName("lbBot")
        self.gridLayout.addWidget(self.lbBot, 0, 1, 1, 1)
        self.txtBot = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtBot.setFont(font)
        self.txtBot.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.txtBot.setFrameShape(QtWidgets.QFrame.Box)
        self.txtBot.setLineWidth(3)
        self.txtBot.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBot.setObjectName("txtBot")
        self.gridLayout.addWidget(self.txtBot, 1, 0, 1, 3)
        self.lbHuman = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.lbHuman.setFont(font)
        self.lbHuman.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lbHuman.setAlignment(QtCore.Qt.AlignCenter)
        self.lbHuman.setObjectName("lbHuman")
        self.gridLayout.addWidget(self.lbHuman, 2, 1, 1, 1)
        self.chatHuman = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.chatHuman.setFont(font)
        self.chatHuman.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.chatHuman.setFrameShape(QtWidgets.QFrame.Box)
        self.chatHuman.setLineWidth(3)
        self.chatHuman.setAlignment(QtCore.Qt.AlignCenter)
        self.chatHuman.setObjectName("chatHuman")
        self.gridLayout.addWidget(self.chatHuman, 3, 0, 1, 3)
        self.btStart = QtWidgets.QPushButton(self.centralwidget)
        self.btStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btStart.setObjectName("btStart")
        self.gridLayout.addWidget(self.btStart, 4, 0, 1, 1)
        self.btStop = QtWidgets.QPushButton(self.centralwidget)
        self.btStop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btStop.setObjectName("btStop")
        self.gridLayout.addWidget(self.btStop, 4, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbBot.setText(_translate("MainWindow", "BOT"))
        self.txtBot.setText(_translate("MainWindow", "......"))
        self.lbHuman.setText(_translate("MainWindow", "Human"))
        self.chatHuman.setText(_translate("MainWindow", "......"))
        self.btStart.setText(_translate("MainWindow", "Start"))
        self.btStop.setText(_translate("MainWindow", "Stop"))
